name = "Boys and the Hoods"
author = "Sehnryr"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2adeb07723fbe8c4bd7331c0d36ce7084966660b3a072149c0e450d880ac0f1f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
