name = "Boys and the Hoods"
author = "Sehnryr"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fc6a38d26bda9eb9f878ee19763d11e107e2aea179d08ab4e8422f5f4815fc5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
