name = "Boys and the Hoods"
author = "Sehnryr"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b9ba9e23bdb73471618a144c5b9cd5a04b982bdfff5fbfe56cc92f30072fc93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
